"""Installation-related doit tasks."""

from typing import Any

from doit.tools import title_with_actions

from .install_tools import create_install_task

_DIRENV_POST_INSTALL_MESSAGE = (
    "\nIMPORTANT: Add direnv hook to your shell:\n"
    "  Bash: echo 'eval \"$(direnv hook bash)\"'\n"
    "  Zsh:  echo 'eval \"$(direnv hook zsh)\"'"
)


def task_install() -> dict[str, Any]:
    """Install package with dependencies."""
    return {
        "actions": [
            "uv sync",
        ],
        "title": title_with_actions,
    }


def task_install_dev() -> dict[str, Any]:
    """Install package with dev dependencies.

    Also marks src/package_name/_version.py as assume-unchanged so that
    the version file regenerated by setuptools-scm during editable installs
    does not appear as modified in git status.
    """
    return {
        "actions": [
            "uv sync --all-extras --dev",
            "git update-index --assume-unchanged src/package_name/_version.py",
        ],
        "title": title_with_actions,
    }


def task_install_direnv() -> dict[str, Any]:
    """Install direnv for automatic environment loading."""
    return create_install_task(
        name="direnv",
        repo="direnv/direnv",
        asset_patterns={"linux": "direnv.linux-amd64"},
        version_cmd=["direnv", "--version"],
        post_install_message=_DIRENV_POST_INSTALL_MESSAGE,
    )
