name: 🔧 Refactor Request
description: Propose code refactoring or improvement
title: "refactor: "
labels: ["refactor", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for proposing a refactoring! This helps improve code quality and maintainability.

  - type: input
    id: title
    attributes:
      label: Refactor Title
      description: "Use format: refactor: <brief description>"
      placeholder: "refactor: extract duplicate validation logic"
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: Current Situation
      description: Describe the current code structure or pattern that needs refactoring
      placeholder: |
        Describe what code/pattern currently exists and where it's located.
        Example: "The validation logic in src/module.py is duplicated across 5 functions..."
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: Describe how you propose to refactor the code
      placeholder: Describe the refactoring approach...
    validations:
      required: true

  - type: textarea
    id: technical-debt
    attributes:
      label: Technical Debt Impact
      description: What technical debt does this address? What are the consequences of not refactoring?
      placeholder: |
        - Maintainability issues
        - Testing challenges
        - Performance concerns
        - Code duplication
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex is this refactoring? (1=trivial, 10=extremely complex)
      options:
        - "1 - Trivial"
        - "2"
        - "3 - Simple"
        - "4"
        - "5 - Moderate"
        - "6"
        - "7 - Complex"
        - "8"
        - "9 - Very Complex"
        - "10 - Extremely Complex"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this refactoring?
      options:
        - "🔴 CRITICAL - Blocking development"
        - "🟠 HIGH - Causing significant issues"
        - "🟡 MEDIUM - Should be addressed soon"
        - "🟢 LOW - Nice to have"
    validations:
      required: true

  - type: textarea
    id: affected-areas
    attributes:
      label: Affected Code Areas
      description: List files, modules, or components that would be affected
      placeholder: |
        - src/module1.py
        - src/module2.py
        - tests/test_module.py
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What improvements will this refactoring bring?
      placeholder: |
        - Improved code readability
        - Easier testing
        - Better performance
        - Reduced duplication
    validations:
      required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Impact Assessment
      description: Check all that apply
      options:
        - label: This may introduce breaking changes
          required: false
        - label: This requires test updates
          required: false
        - label: This requires documentation updates
          required: false
        - label: This affects public API
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, code examples, or references
      placeholder: Additional information...
    validations:
      required: false
